apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-cli-to-db
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: service-mesh-database
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/secure-db-platform/sa/user-dev"]