apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-inserter
  namespace: {{.Values.namespace.name}}
spec:
  schedule: "{{.Values.cronjobs.dataInsert.schedule}}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: user-dev
          containers:
            - name: insert
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: postgres-user
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: postgres-password
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: postgres-db
              command:
                - /bin/sh
                - -c
                - |
                  psql -h service-mesh-database -c "INSERT INTO test (data) VALUES ('auto');"
          restartPolicy: OnFailure