apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{.Values.namespace.name}}
type: Opaque
data:
  postgres-user: bXl1c2Vy        # base64 for 'myuser'
  postgres-password: bXlwYXNzd29yZA==  # base64 for 'mypassword'
  postgres-db: bXlkYg==          # base64 for 'mydb'
