apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-mesh-database.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "service-mesh-database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "service-mesh-database.selectorLabels" . | nindent 4 }}
