apiVersion: v1
kind: Pod
metadata: 
  name: user-cli
  namespace: {{ .Values.namespace.name }}
  labels: 
    app: user-cli
spec:
  serviceAccountName: user-dev
  containers:
    - name: user-cli-container
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
